"""
Let S be the message size generated by layer N+1, M be the maximum packet size for a packet generated by layer N (and handed over to layer N-1), and O the size of the per-packet overhead of a layer N packet. All the sizes are given in bytes. Please find a general expression for the number of fragments generated, which involves only the parameters S, M, and O and one of the functions ceil, floor. Please implement this function in Python.
"""
import math
def number_fragments (messageSize_bytes, overheadPerPacket_bytes, maximumNPacketSize_bytes):
    s = messageSize_bytes
    o = overheadPerPacket_bytes
    m = maximumNPacketSize_bytes
    maxDataSize = m - o
    nPkts = s / maxDataSize
    return math.ceil(nPkts)

print (number_fragments(10000, 100, 1000))