"""
In situations where packet errors are generated by random transient disturbances on a transmission medium, one often finds information about the probability that a single bit is flipped, this probability is called bit error probability or bit error rate. Assuming that a packet consists of L bits and all bits of the packet are flipped independently of each other and with the same probability p, please find an expression for the resulting probability that a packet of L bits is erroneous (i.e. has at least one flipped bit) and implement it in a Python function.
"""
def per_from_ber (bitErrorProb, packetLen_b):
    return 1-((1-bitErrorProb)**packetLen_b)

print ("{:.3f}".format(per_from_ber(0.0001, 1000)))